Repository fusionjs/fusion-plugin-styletron-react, pull requests merged in 2018-10, with the labels that each got.

#155 Release v2.5.3
  package.json
Labels: release

#158 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#161 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
